spring:
  application:
    name: notification
  config:
    import:
    - optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
